---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: noderefreshes.stable.rk.ai
spec:
  group: stable.rk.ai
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                tier:
                  type: string
  scope: Namespaced
  names:
    plural: noderefreshes
    singular: noderefresh
    kind: NodeRefresh